-- =============================================================================
--  bRC2
--    by: BurstBiscuit
--        Xsear
-- =============================================================================

c_Emotes = {
    apologize       = true,
    bask            = true,
    beg             = true,
    belch           = true,
    blowkiss        = true,
    bow             = true,
    calm            = true,
    charge          = true,
    cheer           = true,
    chicken         = true,
    chug            = true,
    congrats        = true,
    cough           = true,
    cry             = true,
    cutthroat       = true,
    dance           = true,
    fear            = true,
    fingerwag       = true,
    flirt           = true,
    gloat           = true,
    groan           = true,
    haiku           = true,
    halt            = true,
    highfive        = true,
    hug             = true,
    joke            = true,
    laugh           = true,
    lookself        = true,
    no              = true,
    roar            = true,
    sad             = true,
    salute          = true,
    search          = true,
    sick            = true,
    sigh            = true,
    sleep           = true,
    sneeze          = true,
    surprise        = true,
    talk            = true,
    taunt           = true,
    thank           = true,
    tikidance       = true,
    tired           = true,
    townstand1      = true,
    townstand2      = true,
    townstand3      = true,
    townstand4      = true,
    townstand5      = true,
    townstand6      = true,
    utility         = true,
    victory         = true,
    watch           = true,
    wave            = true,
    whistle         = true,
    yawn            = true,
    yes             = true
}
